[versions]
compottie = "2.0.2"
mediaPlayerKMP = "2.1.0"

buildkonfigGradlePlugin = "0.17.1"

humanReadable = "1.12.1"
permissionsCompose = "0.20.1"
room = "2.8.4"

composeKmp = "1.10.0-rc02"

koinComposeMultiplatform = "4.1.1"
kotlinGradlePlugin = "2.2.20"
ktor = "3.3.3"

kermit = "2.0.8"

agp = "8.13.1"
icu4j = "78.1"
kotlin = "2.2.21"
ksp = "2.3.2"
coreKtx = "1.17.0"
splashScreen = "1.2.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
composeConstraintlayout = "1.1.1"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
reactiveAndroid = "2.1.1"
reactiveJava = "2.2.21"

coroutinesCore = "1.10.2"
serializationJson = "1.9.0"
serializationPlugin = "2.2.21"
graphQLJava = "25.0"

lottie = "6.7.1"

composeMedia = "1.8.0"
composeVideo = "1.0.50"
composePaging = "3.3.6"

uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
baselineprofile = "1.4.1"
profileinstaller = "1.4.1"
testng = "7.11.0"
multidex = "2.0.1"
exifinterface = "1.4.2"
securityCryptoKtxVersion = "1.1.0"

connectivity = "2.3.0"

[bundles]
ktor-common = ["ktor-client-core", "ktor-client-json", "ktor-client-logging", "ktor-client-serialization", "ktor-client-content-negotiation", "ktor-serialization"]
compose-full = [
    "compose-animation", "compose-animationGraphics", "compose-foundation", "compose-ui",
    "compose-runtime", "compose-runtimeSaveable", "compose-material3", "compose-material", "compose-navigation-suite", "compose-material-icon-core",
    "compose-resources", "compose-material-icon-extended", "androidx-navigation-compose",
]
fileKit = [
    "kmp-filekit-core",
    "kmp-filekit-dialogs",
    "kmp-filekit-dialogs-compose",
    "kmp-filekit-coil"
]

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlin-serialization-gradle = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
compose-compiler-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-gradle = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "composeKmp" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
buildkonfig-gradle-plugin = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfigGradlePlugin" }
human-readable = { module = "nl.jacobras:Human-Readable", version.ref = "humanReadable" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

kmp-prefs = { module = "com.russhwolf:multiplatform-settings", version = "1.3.0" }

koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeMultiplatform" }
koin-compose-viewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinComposeMultiplatform" }
koin-compose-viewModel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koinComposeMultiplatform" }

ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "composeKmp" }
urlencoder = { module = "net.thauvin.erik.urlencoder:urlencoder-lib", version = "1.6.0" }

saved-state = { module = "org.jetbrains.androidx.savedstate:savedstate", version = "1.4.0" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging-jvm = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-logging-ios = { group = "io.ktor", name = "ktor-client-logging-native", version.ref = "ktor" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }

ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

compose-animation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "composeKmp" }
compose-animationGraphics = { group = "org.jetbrains.compose.animation", name = "animation-graphics", version.ref = "composeKmp" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "composeKmp" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "composeKmp" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "composeKmp" }
compose-runtimeSaveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "composeKmp" }
compose-material = { group = "org.jetbrains.compose.material", name = "material", version.ref = "composeKmp" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version = "1.9.0" }
compose-navigation-suite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version = "1.9.0" }
compose-material-icon-core = { group = "org.jetbrains.compose.material", name = "material-icons-core", version = "1.7.3" }
compose-material-icon-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version = "1.7.3" }
compose-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "composeKmp" }
compose-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "composeKmp" }

compose-video-kmp = { module = "network.chaintech:compose-multiplatform-media-player", version.ref = "composeVideo" }
compose-media-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "composeMedia" }
compose-media-session = { group = "androidx.media3", name = "media3-session", version.ref = "composeMedia" }
compose-media-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "composeMedia" }
compose-media-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "composeMedia" }

compose-resources-android = { group = "org.jetbrains.compose.components", name = "components-resources-android", version.ref = "composeKmp" }
compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "composeKmp" }

compose-pdf-viewer = { group = "io.github.grizzi91", name = "bouquet", version = "1.1.3" }

androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.9.1" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationUiKtx" }
compose-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintlayout" }

google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }

lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
#https://coil-kt.github.io/coil/svgs/
kmp-coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version = "3.3.0" }
kmp-coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version = "3.3.0" }
kmp-coil-network-core = { module = "io.coil-kt.coil3:coil-network-core", version = "3.3.0" }
kmp-coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version = "3.3.0" }

kmp-permissions = { module = "dev.icerock.moko:permissions", version = "permissionsCompose" }
kmp-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "permissionsCompose" }
kmp-permissions-bluetooth = { module = "dev.icerock.moko:permissions-bluetooth", version.ref = "permissionsCompose" }
kmp-permissions-camera = { module = "dev.icerock.moko:permissions-camera", version.ref = "permissionsCompose" }
kmp-permissions-contacts = { module = "dev.icerock.moko:permissions-contacts", version.ref = "permissionsCompose" }
kmp-permissions-gallery = { module = "dev.icerock.moko:permissions-gallery", version.ref = "permissionsCompose" }
kmp-permissions-location = { module = "dev.icerock.moko:permissions-location", version.ref = "permissionsCompose" }
kmp-permissions-microphone = { module = "dev.icerock.moko:permissions-microphone", version.ref = "permissionsCompose" }
kmp-permissions-motion = { module = "dev.icerock.moko:permissions-motion", version.ref = "permissionsCompose" }
kmp-permissions-notifications = { module = "dev.icerock.moko:permissions-notifications", version.ref = "permissionsCompose" }
kmp-permissions-storage = { module = "dev.icerock.moko:permissions-storage", version.ref = "permissionsCompose" }


kmp-media = { module = "dev.icerock.moko:media", version = "0.11.1" }
kmp-media-compose = { module = "dev.icerock.moko:media-compose", version = "0.11.1" }

kmp-connectivity-status = { module = "com.github.ln-12:multiplatform-connectivity-status", version = "1.3.0" }

kmp-reveal = { module = "com.svenjacobs.reveal:reveal-core", version = "4.0.0" }

kmp-reach-editor = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version = "1.0.0-rc13" }

kmp-uri = { module = "com.eygraber:uri-kmp", version = "0.0.21" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

reactive-kotlin = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "reactiveAndroid" }
reactive-java = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "reactiveJava" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.7.1" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesCore" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesCore" }

serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
graphql-java = { group = "com.graphql-java", name = "graphql-java", version.ref = "graphQLJava" }

shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version = "1.3.3" }

installreferrer = { group = "com.android.installreferrer", name = "installreferrer", version = "2.2" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

androidx-browser = { group = "androidx.browser", name = "browser", version = "1.9.0" }
android-browser-helper = { group = "com.google.androidbrowserhelper", name = "androidbrowserhelper", version = "2.6.2" }

libphonenumber = { module = "io.github.luca992.libphonenumber-kotlin:libphonenumber", version = "0.1.9" }
testng = { group = "org.testng", name = "testng", version.ref = "testng" }

multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

kmp-locale = { module = "com.vanniktech:multiplatform-locale", version = "0.9.0" }


androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }

#https://github.com/cashapp/multiplatform-paging/issues
paging-android-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "composePaging" }
paging-android-common = { group = "androidx.paging", name = "paging-common", version.ref = "composePaging" }
paging-android-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "composePaging" }

paging-common = { group = "app.cash.paging", name = "paging-common", version = "3.3.0-alpha02-0.5.1" }
paging-compose-common = { group = "app.cash.paging", name = "paging-compose-common", version = "3.3.0-alpha02-0.5.1" }

paging-ios = { group = "app.cash.paging", name = "paging-runtime-uikit", version = "3.3.0-alpha02-0.5.1" }


compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
compottie-dot = { module = "io.github.alexzhirkevich:compottie-dot", version.ref = "compottie" }
compottie-network = { module = "io.github.alexzhirkevich:compottie-network", version.ref = "compottie" }
compottie-resources = { module = "io.github.alexzhirkevich:compottie-resources", version.ref = "compottie" }
androidx-security-crypto-ktx = { group = "androidx.security", name = "security-crypto-ktx", version.ref = "securityCryptoKtxVersion" }

kmp-currency = { module = "io.fluidsonic.currency:fluid-currency", version = "0.13.0" }
kmp-country = { module = "io.fluidsonic.country:fluid-country", version = "0.13.0" }


kmp-filekit-core = { module = "io.github.vinceglb:filekit-core", version = "0.12.0" }
kmp-filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version = "0.12.0" }
kmp-filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version = "0.12.0" }
kmp-filekit-coil = { module = "io.github.vinceglb:filekit-coil", version = "0.12.0" }
alert-kmp = { module = "io.github.khubaibkhan4:mediaplayer-kmp", version.ref = "mediaPlayerKMP" }


connectivity-core = { module = "dev.jordond.connectivity:connectivity-core", version.ref = "connectivity" }
connectivity-device = { module = "dev.jordond.connectivity:connectivity-device", version.ref = "connectivity" }
connectivity-android = { module = "dev.jordond.connectivity:connectivity-android", version.ref = "connectivity" }
connectivity-apple = { module = "dev.jordond.connectivity:connectivity-apple", version.ref = "connectivity" }
connectivity-http = { module = "dev.jordond.connectivity:connectivity-http", version.ref = "connectivity" }
connectivity-compose = { module = "dev.jordond.connectivity:connectivity-compose", version.ref = "connectivity" }
connectivity-compose-device = { module = "dev.jordond.connectivity:connectivity-compose-device", version.ref = "connectivity" }
connectivity-compose-http = { module = "dev.jordond.connectivity:connectivity-compose-http", version.ref = "connectivity" }


[plugins]
android-application = { id = "com.android.application" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android" }
java-library = { id = "java-library" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPlugin" }
parcelize = { id = "kotlin-parcelize" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose" }
android-library = { id = "com.android.kotlin.multiplatform.library" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }

composeMultiplatform = { id = "org.jetbrains.compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
cocoaPods = { id = "org.jetbrains.kotlin.native.cocoapods" }

room = { id = "androidx.room", version.ref = "room" }
